"""add_profile_visibility

Revision ID: d429015be5a0
Revises: 11ef33fb4430
Create Date: 2026-06-01 15:35:44.654070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd429015be5a0'
down_revision: Union[str, None] = '11ef33fb4430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_categories_name', 'categories', type_='unique')
    op.drop_index('ix_categories_name', table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.add_column('users', sa.Column('profile_visibility', sa.String(length=32), server_default='public', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_unique_constraint('uq_categories_name', 'categories', ['name'])
    op.drop_column('users', 'profile_visibility')
    # ### end Alembic commands ###
